### ISSUE TITLE
No ads are displayed.

### ISSUE THREAD

**Issue by alexeyvolkov-dev** [fyber-engineering/fairbid-sample-app-ios#18]
Just cloned the project.
The app shows errors like this:
Ad request completed with no fill - adType:banner placement:197407|BannerPlacementIdExample
Waterfall:
  Rank | Network           | State   | Latency | Price    | TPN placement
-------+-------------------+---------+---------+----------+-------------- {(
)}
        0  | Fyber Marketplace | no fill |    0.16 |    0.000 | 197407

Please help.

**Comment by saschabienert** [comment]
The sample app is running a real auction for an ad and there is no guarantee that an ad network will place a bid. You can try again or add some more mediated networks following our guide: https://developer.fyber.com/hc/en-us/sections/360002896737-FairBid-Mediation.
